# Generated by Django 3.0.5 on 2021-04-23 10:28

import Products.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80)),
                ('price', models.FloatField()),
                ('quantity', models.IntegerField()),
                ('description', models.CharField(max_length=500)),
                ('brand', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to=Products.models.get_image_filename, verbose_name='image')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
